### ISSUE TITLE
Plugin breaks Grails 3.2.11

### ISSUE THREAD

**Issue by hugheba** [javamelody/grails-melody-plugin#43] opened 2017-06-28 15:54 UTC
If you create a fresh Grails 3.2.11 project and add the dependency

`runtime 'org.grails.plugins:grails-melody-plugin:1.67.0'`

You'll get errors with Taglibs.

I created a simple view with a g:link and am getting this error.

`2017-06-28 11:46:53.983 ERROR --- [nio-8972-exec-1] .a.c.c.C.[.[.[.[grailsDispatcherServlet] : Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/index/index.gsp:12] Error executing tag <g:link>: No signature of method: java.lang.String.encodeAsHTML() is applicable for argument types: () values: []
Possible solutions: encodeAsHex(), encodeAsSHA1(), encodeAsMD5(), encodeAsSHA256()] with root cause

groovy.lang.MissingMethodException: No signature of method: java.lang.String.encodeAsHTML() is applicable for argument types: () values: []
Possible solutions: encodeAsHex(), encodeAsSHA1(), encodeAsMD5(), encodeAsSHA256()`

Mac OS X 10.12.5
Java 1.8.131
Grails 3.2.11

**Comment by evernat** [comment] 2017-07-01 20:48
Sorry, I do not reproduce the issue.
By using the sample project at https://github.com/evernat/grails-ssl it works correctly with Grails 3.2.11 and Java 1.8. https://localhost:8443/ and https://localhost:8443/monitoring are OK.
What would cause this sample project to break?

**Comment by jglapa** [comment] 2017-07-05 12:48
@evernat just add `<g:link controller="test">foo</g:link>` to index.gsp and it will start throwing the exception

**Comment by jglapa** [comment] 2017-07-05 12:52
This was also raise by me in grails repo: https://github.com/grails/grails-core/issues/10715

**Comment by demon101** [comment] 2017-07-09 18:42
I got the same bug. 
Can be reproduced by line in  BootStrap.init:
**"some text".encodeAsLink()**

**Comment by demon101** [comment] 2017-07-09 18:46
@graemerocher suggested in https://github.com/grails/grails-core/issues/10715:

> My guess is something to do with the Groovy version, Groovy 2.4.11 is used in 3.2.11

**Comment by evernat** [comment] 2017-07-09 23:13
As said in https://github.com/grails/grails-core/issues/10715#issuecomment-313971674, it seems to be caused by a regression between groovy 2.4.8 and groovy 2.4.9.
To workaround the issue, you may want to add `compile 'org.codehaus.groovy:groovy-all:2.4.8'` in the dependencies of the build.gradle file of your app.

**Comment by demon101** [comment] 2017-07-10 06:17
@evernat using groovy 2.4.8 with grails 3.2  -- bad idea. For example, performance of groovy 2.4.10 has been improved by 15-20 %.

Do you plan to fix the plugin?

**Comment by graemerocher** [comment] 2017-07-10 06:41
I recommend reporting the issue to the Groovy issue tracker https://github.com/grails/grails-core/issues/10715

**Comment by jglapa** [comment] 2017-07-12 10:55
@evernat would it be possible to test the following:
* upgrade the current plugin to grails 3.2.11 (it's 3.1.6 right now https://github.com/javamelody/grails-melody-plugin/blob/master/gradle.properties#L1) 
* build a snapshot
* test that snapshot version with a currently failing example project

Perhaps the issue goes away if the plugin itself is build by groovy > 2.4.9 ?

**Comment by evernat** [comment] 2017-07-12 23:50
@jglapa @sergiomichels 
It seems that building the grails-melody-plugin with the following in gradle.properties of the plugin fixes this issue:
```
grailsVersion=3.2.11
grailsWrapperVersion=1.0.0
gradleWrapperVersion=3.4.1
```
But I am not sure of what I was doing in the plugin for testing this. Sergio, could you check that this change in the plugin will fix the error displayed by the sample project: https://github.com/evernat/grails-ssl ?

**Comment by jglapa** [comment] 2017-07-24 06:16
@evernat https://github.com/grails/grails-core/issues/10715#issuecomment-317304931

**Comment by jukin-jerry** [comment] 2017-08-01 07:44
Created https://github.com/javamelody/grails-melody-plugin/pull/50

**Comment by jukin-jerry** [comment] 2017-08-02 02:45
The Pull Request (50) above does indeed fix the problem described in this ticket under Grails 3.3.0, but a new problem emerges: now melody does not load at startup.  The only other change is upgrading the java-melody-core dependency to 1.68.1.

Here are the messages at application startup, indicating the problem. 

2017-08-02 02:42:16.422  INFO 11581 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@4443b126: startup date [Wed Aug 02 02:42:16 UTC 2017]; root of context hierarchy
2017-08-02 02:42:18.038  WARN 11581 --- [  restartedMain] org.grails.plugins.CorePluginFinder      : [GrailsPluginManager] Core plugin [grails.melody.plugin.GrailsMelodyPluginGrailsPlugin] not found, resuming load without..

**Comment by evernat** [comment] 2017-10-25 22:16
PR #50 is merged. Thanks to all and in particular to @graemerocher and @bassmartin.

**Closed by evernat** 2017-10-25 22:16 UTC
