### ISSUE TITLE
No value for key [org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy] bound to thread

### ISSUE THREAD

**Issue by bassmartin** [javamelody/grails-melody-plugin#48] opened 2017-07-14 14:44 UTC
See https://github.com/grails/grails-core/issues/10675#issuecomment-315321643

**Comment by evernat** [comment] 2017-07-14 14:53
This issue can't be understood.
Please give a sample project to reproduce the issue.

**Comment by bassmartin** [comment] 2017-07-14 14:55
https://github.com/bassmartin/example-newSession-fail

**Comment by bassmartin** [comment] 2017-07-14 14:56
Issue happens when there is a `withNewSession{}` call

**Comment by evernat** [comment] 2017-07-15 00:03
I see no error like you said.
When testing the app, the only thing is:
Condition not satisfied:
true == false
     |
     false
	at migration_grails_3_2_11.TestNewSessionSpec.test something(TestNewSessionSpec.groovy:20)

Closing the issue as invalid.

**Comment by bassmartin** [comment] 2017-07-15 00:06
I'll check Monday

**Comment by jglapa** [comment] 2017-08-01 11:35
I'm also affected by this issue but cannot provide a working reproducible example. The problem goes away once I remove the plugin ( did it for now also due to #50).
I know this is not helpful but the issue exists and perhaps shouldn't be immediately closed.
I would suggest leaving it open and request for a reproducible example.

**Comment by demon101** [comment] 2017-08-01 12:17
@bassmartin could you help with example, please

**Comment by bassmartin** [comment] 2017-08-01 12:55
@demon101 on it

**Comment by bassmartin** [comment] 2017-08-01 13:01
@evernat @demon101 see https://github.com/bassmartin/example-newSession-fail (same project as before).

The test to check is : migration_grails_3_2_11.TestNewSessionIntegrationSpec

**Comment by evernat** [comment] 2017-08-02 22:23
@jglapa
I see no point to leave an issue open when the provided project at that time did not reproduce the issue.
As an author on my free time, it takes enough time to test issues without having to negotiate with reporters.

@bassmartin 
Thanks for the updated sample project. Will see that.

**Comment by jglapa** [comment] 2017-08-03 09:57
@evernat Your opensource contribution is much appreciated. 
I just really would like that issue to be fixed.  With you closing it I cannot track it any more. 
I won't be notified about any new issues concerning it.

**Comment by bassmartin** [comment] 2017-10-24 02:10
Removing `bean.targetDataSource = JdbcWrapper.SINGLETON.createDataSourceProxy(bean.targetDataSource)` makes the test of my sample project work.

As stated by Graeme : 

> It is replacing the data source with another proxy which interferes with the references GORM uses to bind and unbind the session. See
> 
> https://github.com/javamelody/grails-melody-plugin/blob/master/src/main/groovy/grails/melody/plugin/GrailsMelodyPluginGrailsPlugin.groovy#L49

Any idea how we could fix that?

**Comment by bassmartin** [comment] 2017-10-24 16:29
@sergiomichels 
I reverted back to the BeanPostProcessor way to listen to dataSources. I see SQL queries loggued and no issue with LazyDataSource...

Is the BeanPostProcessor now the correct way to do this? Why was this changed back then?

https://github.com/javamelody/grails-melody-plugin/commit/ce1ca5b461ec4b17f1d7a086356962849ce0722b

**Comment by sergiomichels** [comment] 2017-10-24 17:32
@bassmartin We have the description of the original bug [here](https://github.com/javamelody/grails-melody-plugin/issues/3). If now it's working now (maybe something changed in Grails core?) I think we can revert it. Could you create a pull request for it?

**Comment by bassmartin** [comment] 2017-10-24 17:35
I tested with only one DataSource (the default one) and it's working.
I have no idea if this is working with multiple datasources.

**Closed** 2017-10-29 16:53 UTC
